"""fix error

Revision ID: 8781ec1e77a4
Revises: 324a552cc4ed
Create Date: 2025-06-18 23:20:10.308547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8781ec1e77a4'
down_revision = '324a552cc4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_ibfk_2'), 'user', ['user_id'], ['user_id'], ondelete='SET NULL')

    # ### end Alembic commands ###
